server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    streams:
      bindings:
        emailsms-in-O:
          destinations: send-communications
          group: ${spring.application.name}
        emailsms-out-0:
          destinations: communication-sent
      kafka:
        binder:
          brokers:
            - localhost:9092
